development:
  adapter: postgresql
  encoding: unicode
  database: elephantthree
  pool: 5
  username: ehamilton
  password:
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: elephantthree
  pool: 5
  username: ehamilton
  password:
  timeout: 5000