development:
  adapter: postgresql
  encoding: unicode
  database: V2.5_development
  pool: 5
  username: mrehamilton
  password:
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: V2.5_test
  pool: 5
  username: mrehamilton
  password:
  timeout: 5000